

services:
  backend:
    build: ./backend
    ports:
      - "4000:3000"
    env_file:
      - .env
    depends_on:
      - frontend

  frontend:
    build: ./frontend
    ports:
      - "5000:5173"
    env_file:
      - .env
